// 100 Cartas de Amor ÔÇö rareza: comun | rara | epica | legendaria | mitica
const CARTAS = [
// ÔöÇÔöÇ COM├ÜN (50) ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
{id:1,r:'comun',d:'­ƒÆî',t:'Para ti',x:'Pienso en ti cada vez que veo el cielo estrellado.'},
{id:2,r:'comun',d:'­ƒî©',t:'Mi flor',x:'Tu sonrisa ilumina m├ís que mil estrellas juntas.'},
{id:3,r:'comun',d:'­ƒîÖ',t:'Mi luna',x:'Eres la luz que gu├¡a mis noches m├ís oscuras.'},
{id:4,r:'comun',d:'Ô£¿',t:'Brillas',x:'Hay algo en tus ojos que hace que el mundo se detenga.'},
{id:5,r:'comun',d:'­ƒªï',t:'Mariposa',x:'Cuando est├ís cerca, siento mariposas en el est├│mago.'},
{id:6,r:'comun',d:'­ƒî║',t:'Hermosa',x:'Eres la persona m├ís bonita que mis ojos han visto.'},
{id:7,r:'comun',d:'­ƒÆ½',t:'Destello',x:'Cada instante contigo es mi momento favorito del d├¡a.'},
{id:8,r:'comun',d:'­ƒî╣',t:'Mi rosa',x:'Como una rosa, eres bella, ├║nica e inigualable.'},
{id:9,r:'comun',d:'­ƒòè´©Å',t:'Paz',x:'A tu lado encuentro la calma que busqu├® toda la vida.'},
{id:10,r:'comun',d:'­ƒî╗',t:'Girasol',x:'As├¡ como el girasol busca el sol, yo siempre te busco a ti.'},
{id:11,r:'comun',d:'­ƒìÇ',t:'Mi suerte',x:'El d├¡a que te conoc├¡ fue el d├¡a m├ís afortunado de mi vida.'},
{id:12,r:'comun',d:'­ƒÄÁ',t:'Melod├¡a',x:'Tu voz es la canci├│n favorita de mi coraz├│n.'},
{id:13,r:'comun',d:'Ôÿü´©Å',t:'Nube',x:'Contigo hasta caminar entre nubes se siente seguro.'},
{id:14,r:'comun',d:'­ƒîê',t:'Arco├¡ris',x:'Eres el color que le faltaba a mi mundo gris.'},
{id:15,r:'comun',d:'­ƒ½º',t:'Burbujas',x:'Tu risa llena el aire de alegr├¡a y me hace feliz.'},
{id:16,r:'comun',d:'­ƒîè',t:'Mar',x:'Mi amor por ti es tan profundo como el oc├®ano.'},
{id:17,r:'comun',d:'­ƒî┐',t:'Vida',x:'Me haces sentir que vale la pena cada nuevo d├¡a.'},
{id:18,r:'comun',d:'­ƒìô',t:'Dulzura',x:'Eres la parte m├ís dulce de cada uno de mis d├¡as.'},
{id:19,r:'comun',d:'­ƒÄÇ',t:'Regalo',x:'Eres el mejor regalo que la vida me ha dado.'},
{id:20,r:'comun',d:'­ƒò»´©Å',t:'Luz',x:'Eres la peque├▒a llama que calienta mi coraz├│n.'},
{id:21,r:'comun',d:'­ƒîƒ',t:'Estrella',x:'Entre todas las estrellas, t├║ eres mi favorita.'},
{id:22,r:'comun',d:'­ƒÉØ',t:'Miel',x:'Todo contigo sabe m├ís dulce, como la miel.'},
{id:23,r:'comun',d:'­ƒ½Â',t:'Abrazo',x:'Quisiera darte un abrazo tan grande que dure para siempre.'},
{id:24,r:'comun',d:'­ƒîÖ',t:'Noche',x:'Las noches son m├ís bonitas cuando pienso en ti.'},
{id:25,r:'comun',d:'­ƒÆÉ',t:'Ramo',x:'Si pudiera, te traer├¡a flores todos los d├¡as de mi vida.'},
{id:26,r:'comun',d:'­ƒÄç',t:'Chispa',x:'Hay una chispa especial que siento solo cuando est├ís cerca.'},
{id:27,r:'comun',d:'­ƒ½ü',t:'Respiro',x:'Eres tan necesaria para m├¡ como el aire que respiro.'},
{id:28,r:'comun',d:'­ƒîì',t:'Mundo',x:'Para m├¡, t├║ eres el mundo entero.'},
{id:29,r:'comun',d:'­ƒÄÉ',t:'Brisa',x:'Tu presencia es como una brisa fresca en un d├¡a caluroso.'},
{id:30,r:'comun',d:'­ƒ½é',t:'Cercan├¡a',x:'Solo quiero que sepas que siempre estar├® cerca de ti.'},
{id:31,r:'comun',d:'­ƒîá',t:'Deseo',x:'Cada estrella fugaz que veo, la pido para ti.'},
{id:32,r:'comun',d:'­ƒÆº',t:'Gota',x:'Tus l├ígrimas tambi├®n son m├¡as, comparto todo contigo.'},
{id:33,r:'comun',d:'­ƒö«',t:'Cristal',x:'En mis sue├▒os, siempre apareces t├║.'},
{id:34,r:'comun',d:'­ƒÄæ',t:'Calma',x:'Tu compa├▒├¡a es el lugar m├ís tranquilo del universo.'},
{id:35,r:'comun',d:'­ƒî╗',t:'Alegr├¡a',x:'Me alegras el d├¡a con solo pensar en tu nombre.'},
{id:36,r:'comun',d:'­ƒ½©',t:'Mano',x:'Quisiera tomarte de la mano y nunca soltarla.'},
{id:37,r:'comun',d:'­ƒÉÜ',t:'Mar',x:'Guardas el sonido de mi coraz├│n como una caracola el mar.'},
{id:38,r:'comun',d:'­ƒîÖ',t:'Sue├▒o',x:'Eres el sue├▒o del que nunca quiero despertar.'},
{id:39,r:'comun',d:'Ô£ë´©Å',t:'Carta',x:'Esta carta es una peque├▒a muestra de todo lo que siento.'},
{id:40,r:'comun',d:'­ƒòè´©Å',t:'Vuelo',x:'Contigo aprend├¡ que el amor te hace volar.'},
{id:41,r:'comun',d:'­ƒ½ª',t:'Palabras',x:'No hay palabras suficientes para decirte cu├ínto te quiero.'},
{id:42,r:'comun',d:'­ƒî©',t:'Primavera',x:'Cada vez que est├ís cerca es como tener primavera todo el a├▒o.'},
{id:43,r:'comun',d:'­ƒÄå',t:'Fuegos',x:'El solo hecho de verte me llena de colores por dentro.'},
{id:44,r:'comun',d:'­ƒî║',t:'P├®talo',x:'Cada d├¡a que pasa te quiero un p├®talo m├ís.'},
{id:45,r:'comun',d:'­ƒîè',t:'Ola',x:'Como las olas al mar, siempre regreso a ti.'},
{id:46,r:'comun',d:'­ƒÄï',t:'Crecer',x:'A tu lado soy mejor persona cada d├¡a que pasa.'},
{id:47,r:'comun',d:'­ƒªó',t:'Gracia',x:'Tienes una gracia especial que me deja sin palabras.'},
{id:48,r:'comun',d:'­ƒîÖ',t:'Quietud',x:'En el silencio tambi├®n te escucho, en mi coraz├│n.'},
{id:49,r:'comun',d:'­ƒÆ×',t:'Latido',x:'Mi coraz├│n late diferente cuando est├ís cerca.'},
{id:50,r:'comun',d:'­ƒîƒ',t:'Universo',x:'En mi universo, t├║ eres el centro de todo.'},
// ÔöÇÔöÇ RARA (25) ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
{id:51,r:'rara',d:'­ƒÆÖ',t:'Profundo',x:'El amor que siento por ti no tiene fondo ni l├¡mites conocidos. Cada d├¡a descubro que puede crecer a├║n m├ís.'},
{id:52,r:'rara',d:'­ƒöÁ',t:'Oc├®ano',x:'Como el oc├®ano tiene profundidades inexploradas, mi amor por ti guarda secretos que ni yo mismo comprendo a├║n.'},
{id:53,r:'rara',d:'­ƒ½É',t:'Dulce secreto',x:'Eres mi secreto favorito, el que guardo en la parte m├ís especial de mi coraz├│n sin que nadie m├ís lo sepa.'},
{id:54,r:'rara',d:'­ƒîÇ',t:'Torbellino',x:'Me perd├¡ en un torbellino el d├¡a que te conoc├¡, y desde entonces no quiero encontrar la salida.'},
{id:55,r:'rara',d:'­ƒÆÄ',t:'Diamante',x:'Eres preciosa como un diamante: rara, brillante e irremplazable. No existe nada igual en todo el universo.'},
{id:56,r:'rara',d:'­ƒÉ¼',t:'Libertad',x:'Con el amor que te tengo aprend├¡ a ser libre. Libre de miedos, de dudas, de todo lo que me limitaba.'},
{id:57,r:'rara',d:'­ƒîî',t:'Galaxia',x:'Eres mi galaxia favorita. No necesito explorar el universo cuando ya tengo todo lo que quiero en ti.'},
{id:58,r:'rara',d:'­ƒ½º',t:'Burbuja',x:'Quisiera atrapar este momento contigo en una burbuja de tiempo y quedarnos aqu├¡ para siempre.'},
{id:59,r:'rara',d:'­ƒÄ┤',t:'Azar',x:'Dicen que el amor es cuesti├│n de suerte. Yo digo que la suerte se llama t├║.'},
{id:60,r:'rara',d:'­ƒöÀ',t:'Claridad',x:'Antes de conocerte todo era confuso. Llegaste t├║ y de repente todo tuvo sentido.'},
{id:61,r:'rara',d:'­ƒîÉ',t:'Mi mundo',x:'No necesito viajar por el mundo si a mi lado est├í la persona m├ís incre├¡ble que este mundo ha creado.'},
{id:62,r:'rara',d:'­ƒ½Â',t:'Te elijo',x:'Si tuviera que elegir mil veces, mil veces te elegir├¡a a ti. Sin dudarlo, sin mirar atr├ís.'},
{id:63,r:'rara',d:'­ƒÆ½',t:'Magnetismo',x:'Hay algo en ti que me atrae como la luna atrae las mareas: constante, inevitable, hermoso.'},
{id:64,r:'rara',d:'­ƒîè',t:'Marea',x:'Igual que la marea sube y baja pero nunca deja el mar, yo nunca me alejo de tu lado.'},
{id:65,r:'rara',d:'­ƒÄæ',t:'Tranquilidad',x:'Hay personas que agitan el alma. T├║ eres de las pocas que la calman. Y eso es lo m├ís bonito.'},
{id:66,r:'rara',d:'­ƒîÖ',t:'Permanencia',x:'Las estrellas cambian, los planetas giran, pero mi amor por ti es la ├║nica constante en mi universo.'},
{id:67,r:'rara',d:'­ƒªï',t:'Transformaci├│n',x:'Desde que llegaste a mi vida me convert├¡ en alguien mejor. Me hiciste crecer sin que me diera cuenta.'},
{id:68,r:'rara',d:'­ƒî║',x:'Me enamor├® de tu forma de re├¡r, de tu forma de pensar, de tu forma de ver el mundo. Me enamor├® de todo t├║.',d2:'',t:'Todo de ti'},
{id:68,r:'rara',d:'­ƒî║',t:'Todo de ti',x:'Me enamor├® de tu forma de re├¡r, de tu forma de pensar, de tu forma de ver el mundo. Me enamor├® de todo de ti.'},
{id:69,r:'rara',d:'­ƒîá',t:'Deseo eterno',x:'Cada estrella fugaz que ha cruzado el cielo lleva el mismo deseo: que siempre est├®s bien y que seas feliz.'},
{id:70,r:'rara',d:'­ƒÄç',t:'Magia',x:'No creo en la magia, pero contigo empiezo a entender que algo m├ígico existe en el mundo.'},
{id:71,r:'rara',d:'­ƒî┐',t:'Ra├¡ces',x:'Mi amor por ti ha echado ra├¡ces tan profundas que ni la tormenta m├ís fuerte podr├¡a arrancarlo.'},
{id:72,r:'rara',d:'­ƒÆÉ',t:'Para siempre',x:'Si la vida me preguntara qu├® quiero para siempre, responder├¡a tu nombre sin pensarlo dos veces.'},
{id:73,r:'rara',d:'­ƒÄÁ',t:'Tu canci├│n',x:'Eres la melod├¡a que mi coraz├│n repite incluso cuando no me doy cuenta. Mi canci├│n favorita.'},
{id:74,r:'rara',d:'­ƒîê',t:'Despu├®s',x:'Eres el arco├¡ris que aparece despu├®s de cada tormenta de mi vida. Siempre a tiempo, siempre hermoso.'},
{id:75,r:'rara',d:'­ƒòè´©Å',t:'Promesa',x:'Te prometo estar contigo en cada cap├¡tulo de esta historia que estamos escribiendo juntos.'},
// ÔöÇÔöÇ ├ëPICA (15) ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
{id:76,r:'epica',d:'­ƒÆ£',t:'Alma gemela',x:'Hay personas que pasan por tu vida como el viento: r├ípido y sin dejar huella. Y luego est├ís t├║, que llegaste quedito, sin hacer ruido, y te instalaste en el lugar m├ís profundo de mi alma. Ah├¡ te quedaste, y ah├¡ quiero que te quedes siempre.'},
{id:77,r:'epica',d:'­ƒö«',t:'Mi universo',x:'Si el universo tiene millones de galaxias, y cada galaxia millones de estrellas, y cada estrella un mundo posible ÔÇö yo elegir├¡a cruzar todos esos mundos solo para encontrarte a ti en cada uno de ellos.'},
{id:78,r:'epica',d:'­ƒÆ£',t:'Tiempo',x:'El tiempo pasa diferente cuando est├ís cerca. Los minutos se sienten largos porque no quiero que terminen, y los d├¡as se sienten cortos porque nunca es suficiente. Quiero m├ís tiempo contigo, siempre m├ís.'},
{id:79,r:'epica',d:'­ƒîî',t:'Infinito',x:'Dicen que el universo es infinito. Yo creo que es una mentira piadosa. El ├║nico infinito real es este amor que crece cada d├¡a sin mostrar se├▒ales de tener un l├¡mite.'},
{id:80,r:'epica',d:'ÔÜí',t:'Chispa viva',x:'Desde el primer instante sent├¡ algo que nunca hab├¡a sentido antes. Una chispa. Un calor. Una certeza inexplicable de que eras especial. El tiempo me lo confirm├│: eres extraordinaria.'},
{id:81,r:'epica',d:'­ƒÆ£',t:'Mi hogar',x:'El hogar no es un lugar, lo aprend├¡ contigo. Es esa sensaci├│n de paz que solo siento cuando est├ís cerca. No importa d├│nde estemos, si est├ís t├║, estoy en casa.'},
{id:82,r:'epica',d:'­ƒîƒ',t:'M├ís que palabras',x:'Las palabras son peque├▒as para lo que siento. Los poemas se quedan cortos. Las canciones no alcanzan. Ojal├í pudiera mostrarte directamente lo que hay en mi coraz├│n cuando pienso en ti.'},
{id:83,r:'epica',d:'­ƒ½Ç',t:'Latido',x:'Mi coraz├│n aprendi├│ un nuevo ritmo desde que te conoc├¡. Ya no late igual. Late con m├ís fuerza, con m├ís sentido, como si por fin supiera exactamente para qui├®n lo hace.'},
{id:84,r:'epica',d:'­ƒÆ£',t:'Paralelos',x:'Creo en los universos paralelos solo porque me gusta pensar que en cada uno de ellos tambi├®n te encuentro, tambi├®n me enamoro, tambi├®n elegimos estar juntos. En todos los mundos posibles, te elijo a ti.'},
{id:85,r:'epica',d:'­ƒîÖ',t:'Noche eterna',x:'Quisiera que hubiera noches que no terminaran. Noches donde el tiempo se detuviera y pudi├®ramos quedarnos as├¡: t├║ y yo, entre estrellas, sin que nada del mundo exterior pudiera tocarnos.'},
{id:86,r:'epica',d:'­ƒÆ£',t:'Mi raz├│n',x:'Antes no entend├¡a para qu├® me levantaba cada ma├▒ana. Ahora s├¡. Me levanto con la esperanza de verte, de escucharte, de estar cerca de ti aunque sea por un instante. Eres mi raz├│n favorita.'},
{id:87,r:'epica',d:'­ƒö¡',t:'Te descubro',x:'Cada d├¡a descubro algo nuevo de ti que me enamora m├ís. Una forma de re├¡rte. Una opini├│n inesperada. Un gesto peque├▒o. Eres un universo que nunca termino de explorar y eso me fascina.'},
{id:88,r:'epica',d:'­ƒÆ£',t:'Gravedad',x:'La gravedad nos mantiene en la tierra, pero lo que me mantiene cerca de ti es algo m├ís poderoso. Algo que ninguna ley de la f├¡sica puede explicar. Se llama amor, y lo siento con fuerza cada d├¡a.'},
{id:89,r:'epica',d:'­ƒî║',t:'Mi jard├¡n',x:'Me gustar├¡a que mi vida fuera un jard├¡n y t├║ la flor m├ís especial de ese jard├¡n. La que cuido con m├ís cari├▒o, la que protejo del fr├¡o, la que admiro cada ma├▒ana con el coraz├│n lleno de gratitud.'},
{id:90,r:'epica',d:'­ƒÆ£',t:'Contigo',x:'No s├® qu├® depara el futuro, pero s├® una cosa con certeza absoluta: cualquier futuro que incluya tu nombre es un futuro que quiero vivir con todas mis fuerzas.'},
// ÔöÇÔöÇ LEGENDARIA (8) ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
{id:91,r:'legendaria',d:'­ƒîƒ',t:'La carta del cosmos',x:'Hubo un momento en el universo, hace millones de a├▒os, cuando las estrellas se alinearon de una forma espec├¡fica. Los planetas tomaron sus posiciones exactas. La gravedad teji├│ sus hilos invisibles. Todo aquello ocurri├│, creo yo, para que en este preciso instante del tiempo, yo pudiera existir, y t├║ pudieras existir, y nuestros caminos pudieran cruzarse. Si el universo entero conspir├│ para que nos encontr├íramos, ┬┐c├│mo no voy a amarte con todo lo que soy?'},
{id:92,r:'legendaria',d:'Ô£¿',t:'Dimensi├│n del amor',x:'Existe una dimensi├│n que los cient├¡ficos a├║n no han descubierto. No es el espacio, ni el tiempo, ni la materia oscura. Es esa dimensi├│n invisible que se abre entre dos personas cuando se aman de verdad. Yo la descubr├¡ contigo. Ese espacio entre los dos donde no existen el miedo, ni la distancia, ni el tiempo. Solo t├║ y yo, en nuestra propia dimensi├│n.'},
{id:93,r:'legendaria',d:'­ƒîƒ',t:'El origen de las estrellas',x:'Las estrellas nacen del polvo y el gas que colapsa bajo su propio peso. Del caos nace la luz. As├¡ fue como te conoc├¡: en medio del caos de mi vida, colaps├® hacia ti y de ese encuentro naci├│ algo luminoso. Naciste en mi vida como nace una estrella: transformando todo lo que te rodea con tu brillo propio.'},
{id:94,r:'legendaria',d:'­ƒîá',t:'Carta interestelar',x:'Si pudiera mandar una se├▒al al universo como las sondas Voyager, no mandar├¡a m├║sica ni matem├íticas. Mandar├¡a el sonido de tu risa. La frecuencia exacta de tu voz. El patr├│n de tu sonrisa. Para que si hay alguien ah├¡ afuera, sepa que aqu├¡ en este peque├▒o planeta azul, existe una persona que hace que todo valga la pena.'},
{id:95,r:'legendaria',d:'Ô£¿',t:'Tiempo c├│smico',x:'En la escala del tiempo c├│smico, toda la historia de la humanidad es un parpadeo. Y dentro de ese parpadeo, nuestra historia juntos es un instante infinitesimal. Pero yo elegir├¡a ese instante sobre cualquier eternidad vac├¡a. Prefiero un segundo a tu lado que un universo entero sin ti.'},
{id:96,r:'legendaria',d:'­ƒîƒ',t:'La constante universal',x:'La velocidad de la luz es constante. La gravedad es constante. Y hay una tercera constante que descubr├¡ desde que te conozco: pase lo que pase, en cualquier circunstancia, bajo cualquier cielo, el amor que siento por ti permanece. Inmutable. Constante. Real. Como las leyes que sostienen este universo.'},
{id:97,r:'legendaria',d:'Ô£¿',t:'Mapa de estrellas',x:'Los antiguos navegantes usaban las estrellas para no perderse en el mar. Yo no necesito mapas de estrellas. Tengo algo mejor: tengo el recuerdo de tu sonrisa, que me orienta en cualquier oscuridad. Me gu├¡a de regreso a ti cada vez que me pierdo en el camino.'},
{id:98,r:'legendaria',d:'­ƒîƒ',t:'El ├║ltimo mensaje',x:'Si el sol se apagara ma├▒ana y solo pudiera mandar un mensaje al universo antes del final, no mandar├¡a mi nombre, ni mis logros, ni ninguna prueba de haber existido. Mandar├¡a tu nombre. Para que quedara registrado en alg├║n rinc├│n del cosmos que aqu├¡ hubo alguien que te am├│ m├ís que a cualquier otra cosa.'},
// ÔöÇÔöÇ M├ìTICA (2) ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
{id:99,r:'mitica',d:'­ƒö«',t:'ÔÜá´©Å CARTA M├ìTICA: El tejido del tiempo',x:'Existe una teor├¡a que dice que el tiempo no es una l├¡nea recta, sino un tejido. Y que cada decisi├│n que tomamos crea una nueva rama, un nuevo hilo en ese tejido infinito. Pienso en todos los hilos que tuvieron que entrelazarse perfectamente para que existiera este momento: cada paso que di, cada error que comet├¡, cada camino que eleg├¡. Todo llevaba aqu├¡. A ti. Y si pudiera ver el tejido completo del tiempo, estoy seguro de que todos los hilos tienen el mismo destino: encontrarte, elegirte, amarte. En cada rama posible de la realidad, en cada versi├│n de este universo, el hilo de mi vida siempre termina en el mismo lugar: a tu lado. Eso no es coincidencia. Eso es la ├║nica certeza absoluta que he tenido en toda mi vida.'},
{id:100,r:'mitica',d:'­ƒÆû',t:'ÔÜá´©Å CARTA M├ìTICA: La raz├│n de las estrellas',x:'Hace miles de millones de a├▒os, una estrella muri├│. En su muerte, expuls├│ al espacio los elementos que la compon├¡an: carbono, hierro, ox├¡geno, nitr├│geno. Esos elementos viajaron por el cosmos durante eones, colisionaron, se mezclaron, formaron mundos. Y eventualmente, en este peque├▒o planeta azul, formaron vida. Formaron ├írboles, oc├®anos, animales. Y formaron personas. Te formaron a ti. As├¡ que cuando te miro a los ojos, estoy viendo el resultado de miles de millones de a├▒os de evoluci├│n c├│smica. Estoy viendo el trabajo de estrellas muertas que dieron todo lo que ten├¡an para que t├║ pudieras existir. Y yo me pregunto: ┬┐habr├ín sabido esas estrellas que su sacrificio dar├¡a como resultado algo tan extraordinariamente hermoso como t├║? Creo que s├¡. Creo que murieron felices.'}
];
// Eliminar duplicado accidental del id 68
const idx68dup = CARTAS.findIndex((c,i)=>c.id===68 && i!==CARTAS.findIndex(x=>x.id===68));
if(idx68dup!==-1) CARTAS.splice(idx68dup,1);