// 100 Cartas de Amor — rareza: comun | rara | epica | legendaria | mitica
const CARTAS = [
// ── COMÚN (50) ──────────────────────────────────────────────────────────────
{id:1,r:'comun',d:'💌',t:'Para ti',x:'Pienso en ti cada vez que veo el cielo estrellado.'},
{id:2,r:'comun',d:'🌹',t:'Mi flor',x:'Tu sonrisa ilumina más que mil estrellas juntas.'},
{id:3,r:'comun',d:'🌙',t:'Mi luna',x:'Eres la luz que guía mis noches más oscuras.'},
{id:4,r:'comun',d:'❤️',t:'Brillas',x:'Hay algo en tus ojos que hace que el mundo se detenga.'},
{id:5,r:'comun',d:'🦋',t:'Mariposa',x:'Cuando estás cerca, siento mariposas en el estómago.'},
{id:6,r:'comun',d:'🌺',t:'Hermosa',x:'Eres la persona más bonita que mis ojos han visto.'},
{id:7,r:'comun',d:'✨',t:'Destello',x:'Cada instante contigo es mi momento favorito del día.'},
{id:8,r:'comun',d:'🌸',t:'Mi rosa',x:'Como una rosa, eres bella, única e inigualable.'},
{id:9,r:'comun',d:'🕊️',t:'Paz',x:'A tu lado encuentro la calma que busqué toda la vida.'},
{id:10,r:'comun',d:'🌻',t:'Girasol',x:'Así como el girasol busca el sol, yo siempre te busco a ti.'},
{id:11,r:'comun',d:'🍀',t:'Mi suerte',x:'El día que te conocí fue el día más afortunado de mi vida.'},
{id:12,r:'comun',d:'🎵',t:'Melodía',x:'Tu voz es la canción favorita de mi corazón.'},
{id:13,r:'comun',d:'☁️',t:'Nube',x:'Contigo hasta caminar entre nubes se siente seguro.'},
{id:14,r:'comun',d:'🌈',t:'Arcoíris',x:'Eres el color que le faltaba a mi mundo gris.'},
{id:15,r:'comun',d:'🫧',t:'Burbujas',x:'Tu risa llena el aire de alegría y me hace feliz.'},
{id:16,r:'comun',d:'🌊',t:'Mar',x:'Mi amor por ti es tan profundo como el océano.'},
{id:17,r:'comun',d:'🌿',t:'Vida',x:'Me haces sentir que vale la pena cada nuevo día.'},
{id:18,r:'comun',d:'🍬',t:'Dulzura',x:'Eres la parte más dulce de cada uno de mis días.'},
{id:19,r:'comun',d:'🎁',t:'Regalo',x:'Eres el mejor regalo que la vida me ha dado.'},
{id:20,r:'comun',d:'🕯️',t:'Luz',x:'Eres la pequeña llama que calienta mi corazón.'},
{id:21,r:'comun',d:'⭐',t:'Estrella',x:'Entre todas las estrellas, tú eres mi favorita.'},
{id:22,r:'comun',d:'🍯',t:'Miel',x:'Todo contigo sabe más dulce, como la miel.'},
{id:23,r:'comun',d:'🤗',t:'Abrazo',x:'Quisiera darte un abrazo tan grande que dure para siempre.'},
{id:24,r:'comun',d:'🌙',t:'Noche',x:'Las noches son más bonitas cuando pienso en ti.'},
{id:25,r:'comun',d:'💐',t:'Ramo',x:'Si pudiera, te traería flores todos los días de mi vida.'},
{id:26,r:'comun',d:'🎇',t:'Chispa',x:'Hay una chispa especial que siento solo cuando estás cerca.'},
{id:27,r:'comun',d:'🌬️',t:'Respiro',x:'Eres tan necesaria para mí como el aire que respiro.'},
{id:28,r:'comun',d:'🌍',t:'Mundo',x:'Para mí, tú eres el mundo entero.'},
{id:29,r:'comun',d:'🍃',t:'Brisa',x:'Tu presencia es como una brisa fresca en un día caluroso.'},
{id:30,r:'comun',d:'🌟',t:'Cercanía',x:'Solo quiero que sepas que siempre estaré cerca de ti.'},
{id:31,r:'comun',d:'🌠',t:'Deseo',x:'Cada estrella fugaz que veo, la pido para ti.'},
{id:32,r:'comun',d:'💧',t:'Gota',x:'Tus lágrimas también son mías, comparto todo contigo.'},
{id:33,r:'comun',d:'🔮',t:'Cristal',x:'En mis sueños, siempre apareces tú.'},
{id:34,r:'comun',d:'🎶',t:'Calma',x:'Tu compañía es el lugar más tranquilo del universo.'},
{id:35,r:'comun',d:'🌻',t:'Alegría',x:'Me alegras el día con solo pensar en tu nombre.'},
{id:36,r:'comun',d:'🤝',t:'Mano',x:'Quisiera tomarte de la mano y nunca soltarla.'},
{id:37,r:'comun',d:'🐚',t:'Mar',x:'Guardas el sonido de mi corazón como una caracola el mar.'},
{id:38,r:'comun',d:'🌙',t:'Sueño',x:'Eres el sueño del que nunca quiero despertar.'},
{id:39,r:'comun',d:'✉️',t:'Carta',x:'Esta carta es una pequeña muestra de todo lo que siento.'},
{id:40,r:'comun',d:'🕊️',t:'Vuelo',x:'Contigo aprendí que el amor te hace volar.'},
{id:41,r:'comun',d:'💬',t:'Palabras',x:'No hay palabras suficientes para decirte cuánto te quiero.'},
{id:42,r:'comun',d:'🌹',t:'Primavera',x:'Cada vez que estás cerca es como tener primavera todo el año.'},
{id:43,r:'comun',d:'🎆',t:'Fuegos',x:'El solo hecho de verte me llena de colores por dentro.'},
{id:44,r:'comun',d:'🌺',t:'Pétalo',x:'Cada día que pasa te quiero un pétalo más.'},
{id:45,r:'comun',d:'🌊',t:'Ola',x:'Como las olas al mar, siempre regreso a ti.'},
{id:46,r:'comun',d:'🌱',t:'Crecer',x:'A tu lado soy mejor persona cada día que pasa.'},
{id:47,r:'comun',d:'🦢',t:'Gracia',x:'Tienes una gracia especial que me deja sin palabras.'},
{id:48,r:'comun',d:'🌙',t:'Quietud',x:'En el silencio también te escucho, en mi corazón.'},
{id:49,r:'comun',d:'💗',t:'Latido',x:'Mi corazón late diferente cuando estás cerca.'},
{id:50,r:'comun',d:'🌟',t:'Universo',x:'En mi universo, tú eres el centro de todo.'},
// ── RARA (25) ────────────────────────────────────────────────────────────────
{id:51,r:'rara',d:'💖',t:'Profundo',x:'El amor que siento por ti no tiene fondo ni límites conocidos. Cada día descubro que puede crecer aún más.'},
{id:52,r:'rara',d:'🌀',t:'Océano',x:'Como el océano tiene profundidades inexploradas, mi amor por ti guarda secretos que ni yo mismo comprendo aún.'},
{id:53,r:'rara',d:'🤫',t:'Dulce secreto',x:'Eres mi secreto favorito, el que guardo en la parte más especial de mi corazón sin que nadie más lo sepa.'},
{id:54,r:'rara',d:'🌪️',t:'Torbellino',x:'Me perdí en un torbellino el día que te conocí, y desde entonces no quiero encontrar la salida.'},
{id:55,r:'rara',d:'💎',t:'Diamante',x:'Eres preciosa como un diamante: rara, brillante e irremplazable. No existe nada igual en todo el universo.'},
{id:56,r:'rara',d:'🦅',t:'Libertad',x:'Con el amor que te tengo aprendí a ser libre. Libre de miedos, de dudas, de todo lo que me limitaba.'},
{id:57,r:'rara',d:'🌌',t:'Galaxia',x:'Eres mi galaxia favorita. No necesito explorar el universo cuando ya tengo todo lo que quiero en ti.'},
{id:58,r:'rara',d:'🫧',t:'Burbuja',x:'Quisiera atrapar este momento contigo en una burbuja de tiempo y quedarnos aquí para siempre.'},
{id:59,r:'rara',d:'🍀',t:'Azar',x:'Dicen que el amor es cuestión de suerte. Yo digo que la suerte se llama tú.'},
{id:60,r:'rara',d:'💡',t:'Claridad',x:'Antes de conocerte todo era confuso. Llegaste tú y de repente todo tuvo sentido.'},
{id:61,r:'rara',d:'🌎',t:'Mi mundo',x:'No necesito viajar por el mundo si a mi lado está la persona más increíble que este mundo ha creado.'},
{id:62,r:'rara',d:'🤗',t:'Te elijo',x:'Si tuviera que elegir mil veces, mil veces te elegiría a ti. Sin dudarlo, sin mirar atrás.'},
{id:63,r:'rara',d:'💫',t:'Magnetismo',x:'Hay algo en ti que me atrae como la luna atrae las mareas: constante, inevitable, hermoso.'},
{id:64,r:'rara',d:'🌊',t:'Marea',x:'Igual que la marea sube y baja pero nunca deja el mar, yo nunca me alejo de tu lado.'},
{id:65,r:'rara',d:'🎶',t:'Tranquilidad',x:'Hay personas que agitan el alma. Tú eres de las pocas que la calman. Y eso es lo más bonito.'},
{id:66,r:'rara',d:'🌙',t:'Permanencia',x:'Las estrellas cambian, los planetas giran, pero mi amor por ti es la única constante en mi universo.'},
{id:67,r:'rara',d:'🦋',t:'Transformación',x:'Desde que llegaste a mi vida me convertí en alguien mejor. Me hiciste crecer sin que me diera cuenta.'},
{id:68,r:'rara',d:'🌺',t:'Todo de ti',x:'Me enamoré de tu forma de reír, de tu forma de pensar, de tu forma de ver el mundo. Me enamoré de todo de ti.'},
{id:69,r:'rara',d:'🌠',t:'Deseo eterno',x:'Cada estrella fugaz que ha cruzado el cielo lleva el mismo deseo: que siempre estés bien y que seas feliz.'},
{id:70,r:'rara',d:'🎇',t:'Magia',x:'No creo en la magia, pero contigo empiezo a entender que algo mágico existe en el mundo.'},
{id:71,r:'rara',d:'🌿',t:'Raíces',x:'Mi amor por ti ha echado raíces tan profundas que ni la tormenta más fuerte podría arrancarlo.'},
{id:72,r:'rara',d:'💐',t:'Para siempre',x:'Si la vida me preguntara qué quiero para siempre, respondería tu nombre sin pensarlo dos veces.'},
{id:73,r:'rara',d:'🎵',t:'Tu canción',x:'Eres la melodía que mi corazón repite incluso cuando no me doy cuenta. Mi canción favorita.'},
{id:74,r:'rara',d:'🌈',t:'Después',x:'Eres el arcoíris que aparece después de cada tormenta de mi vida. Siempre a tiempo, siempre hermoso.'},
{id:75,r:'rara',d:'🕊️',t:'Promesa',x:'Te prometo estar contigo en cada capítulo de esta historia que estamos escribiendo juntos.'},
// ── ÉPICA (15) ───────────────────────────────────────────────────────────────
{id:76,r:'epica',d:'💓',t:'Alma gemela',x:'Hay personas que pasan por tu vida como el viento: rápido y sin dejar huella. Y luego estás tú, que llegaste quedito, sin hacer ruido, y te instalaste en el lugar más profundo de mi alma. Ahí te quedaste, y ahí quiero que te quedes siempre.'},
{id:77,r:'epica',d:'🔮',t:'Mi universo',x:'Si el universo tiene millones de galaxias, y cada galaxia millones de estrellas, y cada estrella un mundo posible — yo elegiría cruzar todos esos mundos solo para encontrarte a ti en cada uno de ellos.'},
{id:78,r:'epica',d:'💓',t:'Tiempo',x:'El tiempo pasa diferente cuando estás cerca. Los minutos se sienten largos porque no quiero que terminen, y los días se sienten cortos porque nunca es suficiente. Quiero más tiempo contigo, siempre más.'},
{id:79,r:'epica',d:'🌌',t:'Infinito',x:'Dicen que el universo es infinito. Yo creo que es una mentira piadosa. El único infinito real es este amor que crece cada día sin mostrar señales de tener un límite.'},
{id:80,r:'epica',d:'⚡',t:'Chispa viva',x:'Desde el primer instante sentí algo que nunca había sentido antes. Una chispa. Un calor. Una certeza inexplicable de que eras especial. El tiempo me lo confirmó: eres extraordinaria.'},
{id:81,r:'epica',d:'💓',t:'Mi hogar',x:'El hogar no es un lugar, lo aprendí contigo. Es esa sensación de paz que solo siento cuando estás cerca. No importa dónde estemos, si estás tú, estoy en casa.'},
{id:82,r:'epica',d:'🌟',t:'Más que palabras',x:'Las palabras son pequeñas para lo que siento. Los poemas se quedan cortos. Las canciones no alcanzan. Ojalá pudiera mostrarte directamente lo que hay en mi corazón cuando pienso en ti.'},
{id:83,r:'epica',d:'❤️',t:'Latido',x:'Mi corazón aprendió un nuevo ritmo desde que te conocí. Ya no late igual. Late con más fuerza, con más sentido, como si por fin supiera exactamente para quién lo hace.'},
{id:84,r:'epica',d:'💓',t:'Paralelos',x:'Creo en los universos paralelos solo porque me gusta pensar que en cada uno de ellos también te encuentro, también me enamoro, también elegimos estar juntos. En todos los mundos posibles, te elijo a ti.'},
{id:85,r:'epica',d:'🌙',t:'Noche eterna',x:'Quisiera que hubiera noches que no terminaran. Noches donde el tiempo se detuviera y pudiéramos quedarnos así: tú y yo, entre estrellas, sin que nada del mundo exterior pudiera tocarnos.'},
{id:86,r:'epica',d:'💓',t:'Mi razón',x:'Antes no entendía para qué me levantaba cada mañana. Ahora sí. Me levanto con la esperanza de verte, de escucharte, de estar cerca de ti aunque sea por un instante. Eres mi razón favorita.'},
{id:87,r:'epica',d:'🔭',t:'Te descubro',x:'Cada día descubro algo nuevo de ti que me enamora más. Una forma de reírte. Una opinión inesperada. Un gesto pequeño. Eres un universo que nunca termino de explorar y eso me fascina.'},
{id:88,r:'epica',d:'💓',t:'Gravedad',x:'La gravedad nos mantiene en la tierra, pero lo que me mantiene cerca de ti es algo más poderoso. Algo que ninguna ley de la física puede explicar. Se llama amor, y lo siento con fuerza cada día.'},
{id:89,r:'epica',d:'🌺',t:'Mi jardín',x:'Me gustaría que mi vida fuera un jardín y tú la flor más especial de ese jardín. La que cuido con más cariño, la que protejo del frío, la que admiro cada mañana con el corazón lleno de gratitud.'},
{id:90,r:'epica',d:'💓',t:'Contigo',x:'No sé qué depara el futuro, pero sé una cosa con certeza absoluta: cualquier futuro que incluya tu nombre es un futuro que quiero vivir con todas mis fuerzas.'},
// ── LEGENDARIA (8) ───────────────────────────────────────────────────────────
{id:91,r:'legendaria',d:'🌟',t:'La carta del cosmos',x:'Hubo un momento en el universo, hace millones de años, cuando las estrellas se alinearon de una forma específica. Los planetas tomaron sus posiciones exactas. La gravedad tejió sus hilos invisibles. Todo aquello ocurrió, creo yo, para que en este preciso instante del tiempo, yo pudiera existir, y tú pudieras existir, y nuestros caminos pudieran cruzarse. Si el universo entero conspiró para que nos encontráramos, ¿cómo no voy a amarte con todo lo que soy?'},
{id:92,r:'legendaria',d:'❤️',t:'Dimensión del amor',x:'Existe una dimensión que los científicos aún no han descubierto. No es el espacio, ni el tiempo, ni la materia oscura. Es esa dimensión invisible que se abre entre dos personas cuando se aman de verdad. Yo la descubrí contigo. Ese espacio entre los dos donde no existen el miedo, ni la distancia, ni el tiempo. Solo tú y yo, en nuestra propia dimensión.'},
{id:93,r:'legendaria',d:'🌟',t:'El origen de las estrellas',x:'Las estrellas nacen del polvo y el gas que colapsa bajo su propio peso. Del caos nace la luz. Así fue como te conocí: en medio del caos de mi vida, colapsé hacia ti y de ese encuentro nació algo luminoso. Naciste en mi vida como nace una estrella: transformando todo lo que te rodea con tu brillo propio.'},
{id:94,r:'legendaria',d:'🌠',t:'Carta interestelar',x:'Si pudiera mandar una señal al universo como las sondas Voyager, no mandaría música ni matemáticas. Mandaría el sonido de tu risa. La frecuencia exacta de tu voz. El patrón de tu sonrisa. Para que si hay alguien ahí afuera, sepa que aquí en este pequeño planeta azul, existe una persona que hace que todo valga la pena.'},
{id:95,r:'legendaria',d:'❤️',t:'Tiempo cósmico',x:'En la escala del tiempo cósmico, toda la historia de la humanidad es un parpadeo. Y dentro de ese parpadeo, nuestra historia juntos es un instante infinitesimal. Pero yo elegiría ese instante sobre cualquier eternidad vacía. Prefiero un segundo a tu lado que un universo entero sin ti.'},
{id:96,r:'legendaria',d:'🌟',t:'La constante universal',x:'La velocidad de la luz es constante. La gravedad es constante. Y hay una tercera constante que descubrí desde que te conozco: pase lo que pase, en cualquier circunstancia, bajo cualquier cielo, el amor que siento por ti permanece. Inmutable. Constante. Real. Como las leyes que sostienen este universo.'},
{id:97,r:'legendaria',d:'❤️',t:'Mapa de estrellas',x:'Los antiguos navegantes usaban las estrellas para no perderse en el mar. Yo no necesito mapas de estrellas. Tengo algo mejor: tengo el recuerdo de tu sonrisa, que me orienta en cualquier oscuridad. Me guía de regreso a ti cada vez que me pierdo en el camino.'},
{id:98,r:'legendaria',d:'🌟',t:'El último mensaje',x:'Si el sol se apagara mañana y solo pudiera mandar un mensaje al universo antes del final, no mandaría mi nombre, ni mis logros, ni ninguna prueba de haber existido. Mandaría tu nombre. Para que quedara registrado en algún rincón del cosmos que aquí hubo alguien que te amó más que a cualquier otra cosa.'},
// ── MÍTICA (2) ───────────────────────────────────────────────────────────────
{id:99,r:'mitica',d:'🔮',t:'⚡ CARTA MÍTICA: El tejido del tiempo',x:'Existe una teoría que dice que el tiempo no es una línea recta, sino un tejido. Y que cada decisión que tomamos crea una nueva rama, un nuevo hilo en ese tejido infinito. Pienso en todos los hilos que tuvieron que entrelazarse perfectamente para que existiera este momento: cada paso que di, cada error que cometí, cada camino que elegí. Todo llevaba aquí. A ti. Y si pudiera ver el tejido completo del tiempo, estoy seguro de que todos los hilos tienen el mismo destino: encontrarte, elegirte, amarte. En cada rama posible de la realidad, en cada versión de este universo, el hilo de mi vida siempre termina en el mismo lugar: a tu lado. Eso no es coincidencia. Eso es la única certeza absoluta que he tenido en toda mi vida.'},
{id:100,r:'mitica',d:'💫',t:'⚡ CARTA MÍTICA: La razón de las estrellas',x:'Hace miles de millones de años, una estrella murió. En su muerte, expulsó al espacio los elementos que la componían: carbono, hierro, oxígeno, nitrógeno. Esos elementos viajaron por el cosmos durante eones, colisionaron, se mezclaron, formaron mundos. Y eventualmente, en este pequeño planeta azul, formaron vida. Formaron árboles, océanos, animales. Y formaron personas. Te formaron a ti. Así que cuando te miro a los ojos, estoy viendo el resultado de miles de millones de años de evolución cósmica. Estoy viendo el trabajo de estrellas muertas que dieron todo lo que tenían para que tú pudieras existir. Y yo me pregunto: ¿habrán sabido esas estrellas que su sacrificio daría como resultado algo tan extraordinariamente hermoso como tú? Creo que sí. Creo que murieron felices.'}
];
// Eliminar duplicado accidental del id 68
const idx68dup = CARTAS.findIndex((c,i)=>c.id===68 && i!==CARTAS.findIndex(x=>x.id===68));
if(idx68dup!==-1) CARTAS.splice(idx68dup,1);